### ISSUE TITLE
大佬...steam直连似乎失效了

### ISSUE THREAD

**Issue by AllForLandlord** [AoEiuV020/SubConfig#1]
如题，我今天偶然发现steam的区域又变成了我代理节点的区域了，请问您的情况怎么样？

**Comment by AoEiuV020** [comment]
我最近倒是没怎么玩steam，晚上回家看看吧，

**Comment by AllForLandlord** [comment]
> 我最近倒是没怎么玩steam，晚上回家看看吧，

非常感谢大佬，麻烦您了！

**Comment by AoEiuV020** [comment]
我这边正常，还是国内，你那边会不会是有其他设备比如手机登录过影响到了，有时候会这样的，
尝试“ 管理 Steam 令牌” -> “取消对其他所有设备的授权” 然后重新登录，
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/11682198/170255319-ff473e0a-3411-4077-a654-d5977665a272.png">

**Comment by AllForLandlord** [comment]
> 我这边正常，还是国内，你那边会不会是有其他设备比如手机登录过影响到了，有时候会这样的，
> 尝试“ 管理 Steam 令牌” -> “取消对其他所有设备的授权” 然后重新登录，
> <img alt="image" width="1920" src="https://user-images.githubusercontent.com/11682198/170255319-ff473e0a-3411-4077-a654-d5977665a272.png">

原来如此，我今天做的操作就是把几个账号给家庭共享了，可能是这个原因吧...我再尝试下，谢谢！

**Comment by AllForLandlord** [comment]
现在正常了，感谢作者！
