### ISSUE TITLE
似乎现在steam直连需要再多加两条规则

### ISSUE THREAD

**Issue by AllForLandlord** [AoEiuV020/SubConfig#2]
刚刚发现用大佬您的规则还是被识别成代理地区，抓包看了一下以后发现现在会在登录时请求两条域名：api.steampowered.com和test.steampowered.com(我用的是DOMAIN-SUFFIX)，我把这两条规则加上后就成功识别成CN了，请大佬看看是不是这样。

**Comment by AllForLandlord** [comment]
尴尬，刚刚看了下加了这两条规则也还是识别成代理服务器的地区了。。。

**Comment by AoEiuV020** [comment]
steam user_info 查到地区不是CN首先退出所有其他设备再退出自己再测，
在“帐户明细”页面的“管理Steam 令牌”中选择“取消对其他所有设备的授权”

**Comment by AllForLandlord** [comment]
> steam user_info 查到地区不是CN首先退出所有其他设备再退出自己再测，
> 在“帐户明细”页面的“管理Steam 令牌”中选择“取消对其他所有设备的授权”

我刚刚已经这么操作过了啊，回头我再试试

**Comment by AllForLandlord** [comment]
> 

现在回家了再试试又好了，不好意思打扰了...
