### ISSUE TITLE
建议修改steam-direct.list

### ISSUE THREAD

**Issue by AllForLandlord** [AoEiuV020/SubConfig#3]
您好！今天我登录steam的时候发现steam的地区变成了翻墙的地区，简单研究一下以后发现steam在登录账号的时候访问了*.steamserver.net，我自己创建规则尝试加入了一行DOMAIN-SUFFIX,steamserver.net 后问题解决了，有时间的话请加入这一行，谢谢您！

**Comment by AoEiuV020** [comment]
好，先加上了用一阵子看看，目前这配置确实感觉时灵时不灵的感觉，

**Comment by AllForLandlord** [comment]
> 好，先加上了用一阵子看看，目前这配置确实感觉时灵时不灵的感觉，

嗯，我看到有位大佬也整理了需要直连的域名，链接如下： https://www.dogfight360.com/blog/knowledge-base/fix_steamdl_region/
