### ISSUE TITLE
steam-direct只需保留四条域名规则

### ISSUE THREAD

**Issue by AllForLandlord** [AoEiuV020/SubConfig#4]
实测现在steam-direct只需保留四条域名规则：
DOMAIN-SUFFIX,cm.steampowered.com
DOMAIN-SUFFIX,steamserver.net
DOMAIN,api.steampowered.com
DOMAIN,test.steampowered.com

下面的IP规则现在都不需要了

**Comment by AoEiuV020** [comment]
是长时间测试了的吗？之前也不是总会出现ip，

**Comment by AllForLandlord** [comment]
> 是长时间测试了的吗？之前也不是总会出现ip，

测试了三四次吧，都没出问题，感觉可以再观察观察，正好也是最近又开始玩游戏了，然后感觉有些连接有点慢，所以在想是不是规则可以继续优化

**Comment by AllForLandlord** [comment]
> 是长时间测试了的吗？之前也不是总会出现ip，

今天又测试了下，应该是没什么问题的了，可以采用
