### ISSUE TITLE
steam-direct优化

### ISSUE THREAD

**Issue by AllForLandlord** [AoEiuV020/SubConfig#5]
没错又是我...
测试了下，steam只需要以下两条规则直连即可：
DOMAIN-SUFFIX,cm.steampowered.com
DOMAIN-SUFFIX,steamserver.net

如果加上剩下两个规则的话，会导致steam登录新账号要扫描二维码或者输入账号密码后按登录无法正常登录。

修改规则后可以正常登录，且测试下来Steam地区为CN。

**Comment by AoEiuV020** [comment]
好坑这东西，我之前加上后两个就是因为确实出现了登录地区不是CN，有时候正常有时候不行的，太折腾了，
总之先按你说的改吧，
